### ISSUE TITLE
PbfWriter does not write visible-flag from metadata

### ISSUE THREAD

**Issue by timm-gatg** [topobyte/osm4j#1]
The bug is in 
PbfWriter:serializeMetadata(OsmEntity entity)

if you compare that with 
XmlWriter:printMetadata(BuilderWriter buf, OsmMetadata metadata)

you'll see that the visible flag was forgotten.

This might also be the potential reason for:
https://lists.openstreetmap.org/pipermail/dev/2017-February/029707.html

**Comment by sebkur** [comment]
Thanks for the report. I just pushed 7411be1c4880bc92715049f059df8f660f642545 with the proposed fixes.

**Comment by timm-gatg** [comment]
Yeah, there is actually a bit more wrong, it seems like the visibility flag is not being read properly in general (as mentioned in that thread). When parsing the full_planet.osm file (86gb as pbf) I get 0 nodes in Berlin that are !visible - from 10959852 in Berlin total.

**Comment by sebkur** [comment]
hmm, I thought this was fixed via da2e4176e098 and b56218994d back in 2017 but maybe there are still problems. Which version are you using?

It is definitely a problem that there are currently no tests implemented that can be used to check osm4j's behavior concerning history files. Would be good to obtain a few very small PBF files that contain visible and non-visible objects for implementing some tests. We would need to use a different tool to generate those files, most likely using osmium or one of its bindings.

**Comment by timm-gatg** [comment]
I think I have found the issue and it was on my end. I assumed a deleted node would still have the same coordinates, so I was not checking if in previous updates of that node, the (now deleted) node was in Berlin. I wasn't aware of the fact that the lat/long of a deleted node gets ... changed, my bad, sorry!

**Comment by sebkur** [comment]
Good to hear that it is working. Anyway you discovered the issue with missing writing of the visible flag in PBF, so thank you for that!

**Comment by timm-gatg** [comment]
You are welcome... in the process I also tried working with https://github.com/woltapp/parallelpbf 
A weird thing is though, that the number of total nodes I get with osm4j and parallelpbf is different (by - iirc - nearly 50%) for the full_planet.osm.pbf file. I looked into both your and their sources but I couldn't see a reason why it should be the case, but I am going with osm4j as this is the one with the higher number of nodes ;-)

**Comment by sebkur** [comment]
Interesting, didn't know about that other library. Maybe part of their [performance gain](https://github.com/woltapp/parallelpbf#performance-comparision) is because they drop some objects during processing ;) Implementing things correctly with concurrency can be a tricky thing.
